### ISSUE TITLE
Error encontrado en JavaScript en linea 71

### ISSUE THREAD

**Issue by SoleMer** [mihaelkyeah/gato-negro-y-pandilla#5]
La función agregarPersona tiene un error en la línea 71: if(validarEmail(campo agregaPEmail)). Se sugiere agregar un .value en el parámetro.

**Comment by FHFraHz** [comment]
Bug arreglado.
`if (validarEmail(campoAgregaPEmail)) {`
reemplazado:
`if (validarEmail(campoAgregaPEmail.value)) {`
